version: "3"

services:
  filebrowser:
    image: fb
    ports:
      - ${PORT}:80
    volumes:
      - /var/lib/docker/volumes:/data
      - instance-storage:/config
    environment:
      - FB_BASEURL=/filebrowser
    restart: always

volumes:
  instance-storage:
    external: false
    name: filebrowser