---
version: "3"
services:
  streamlit:
    network_mode: bridge
    image: ghcr.io/sampingram/csc-streamlit-deploy:latest
    container_name: streamlit-${INSTANCE_ID}
    environment:
      - REPO=${REPO}
      - DIR=${DIR}
      - ENTRY=${ENTRY}
    volumes:
      - ${DIR:-/dev/null}:${DIR:-/dev/null}
    ports:
      - ${ASSIGNED_PORT}:${STREAMLIT_PORT:-8501}
    restart: unless-stopped
