---
version: "1"
services:
  streamlit:
    network_mode: bridge
    image: ghcr.io/sampingram/csc-streamlit-deploy:latest
    container_name: streamlit-${INSTANCE_ID}
    environment:
      - REPO=${REPO}
      - DIR=${DIR}
      - ENTRY=${ENTRY}
    ports:
      - :8501
    restart: unless-stopped
