---
version: "2.1"
services:
  octave-dev:
    network_mode: bridge
    image: ghcr.io/sampingram/csc-octave-code-server-${OCTAVE_VER}:latest
    container_name: octave-dev-${INSTANCE_ID}
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - PASSWORD=${PASSWORD}
      - SUDO_PASSWORD=${SUDO_PASSWORD}
      - DEFAULT_WORKSPACE=/config/workspace
      - DISPLAY=novnc:0.0
    volumes:
      - instance-storage:/config
    ports:
      - :8443
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]
volumes:
  instance-storage:
    external: false
    name: octave-dev-${INSTANCE_ID}