version: '3.1'  # Secrets are only available since this version of Docker Compose
services:
  orthanc:
    image: ghcr.io/sampingram/csc-orthanc-base:latest
    ports:
      - ${DICOM_PORT}:4242
      - ${APP_PORT}:8042
    environment:
      - ORTHANC_NAME=Orthanc_Node-${INSTANCE_ID}
