---
version: "2.1"
services:
  qatrackplus:
    network_mode: bridge
    image: ghcr.io/sampingram/csc-qatrackplus-${QAT_VERSION}:latest
    container_name: qatrackplus-${INSTANCE_ID}
    volumes:
      - instance-storage-pg:/var/lib/postgresql/14/main/
      - instance-storage-qat:/home
    ports:
      - :80
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: "16g"

volumes:
  instance-storage-pg:
    external: false
    name: qatrackplus-pg-${INSTANCE_ID}
  instance-storage-qat:
    external: false
    name: qatrackplus-qat-${INSTANCE_ID}