version: '2'
services:
  ide:
    image: linuxserver/code-server:latest
    environment:
      - DISPLAY=novnc:0.0
    depends_on:
      - novnc
    ports:
      - 5443:5443
    networks:
      - x11
  novnc:  
    image: psharkey/novnc:latest
    environment:
      # Adjust to your screen size
      - DISPLAY_WIDTH=1920
      - DISPLAY_HEIGHT=1080
    ports:
      - 8080:8080
    networks:
      - x11
networks:
  x11: