name: Build & publish csc images
on:
  release:
    types: [published]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-base-images:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./docker/novnc/Dockerfile
            context: ./docker/novnc/
            image: ghcr.io/sampingram/csc-novnc
          - dockerfile: ./docker/code-server-base/Dockerfile
            context: ./docker/code-server-base/
            image: ghcr.io/sampingram/csc-code-server-base
          - dockerfile: ./docker/orthanc-base/Dockerfile
            context: ./docker/orthanc-base/
            image: ghcr.io/sampingram/csc-orthanc-base
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ matrix.image }}

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Build and push Docker images for CSC-Software-Stack
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          build-args: ${{ matrix.buildargs }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  build-and-push-app-images:
    needs: build-and-push-base-images
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./docker/python-code-server/Dockerfile
            context: ./docker/python-code-server/
            image: ghcr.io/sampingram/csc-python-code-server-3.11
            buildargs: PY_VERSION=3.11
          - dockerfile: ./docker/python-code-server/Dockerfile
            context: ./docker/python-code-server/
            image: ghcr.io/sampingram/csc-python-code-server-3.9
            buildargs: PY_VERSION=3.9
          - dockerfile: ./docker/python-code-server/Dockerfile
            context: ./docker/python-code-server/
            image: ghcr.io/sampingram/csc-python-code-server-3.8
            buildargs: PY_VERSION=3.8
          - dockerfile: ./docker/python-code-server/Dockerfile
            context: ./docker/python-code-server/
            image: ghcr.io/sampingram/csc-python-code-server-3.7
            buildargs: PY_VERSION=3.7
          - dockerfile: ./docker/python-code-server/Dockerfile
            context: ./docker/python-code-server/
            image: ghcr.io/sampingram/csc-python-code-server-3.7
            buildargs: PY_VERSION=2.7
          - dockerfile: ./docker/conda-code-server/Dockerfile
            context: ./docker/conda-code-server/
            image: ghcr.io/sampingram/csc-conda-code-server
          - dockerfile: ./docker/octave-code-server/Dockerfile
            context: ./docker/octave-code-server/
            image: ghcr.io/sampingram/csc-octave-code-server-6.4.0
            buildargs: OCTAVE_VER=6.4.0
          - dockerfile: ./docker/octave-code-server/Dockerfile
            context: ./docker/octave-code-server/
            image: ghcr.io/sampingram/csc-octave-code-server-7.3.0
            buildargs: OCTAVE_VER=7.3.0
          - dockerfile: ./docker/octave-code-server/Dockerfile
            context: ./docker/octave-code-server/
            image: ghcr.io/sampingram/csc-octave-code-server-8.2.0
            buildargs: OCTAVE_VER=8.2.0
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ matrix.image }}

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Build and push Docker images for CSC-Software-Stack
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          build-args: ${{ matrix.buildargs }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
