services:
  filebrowser:
    network_mode: bridge
    image: ghcr.io/sampingram/csc-filebrowser:latest
    ports:
      - ${PORT}:80
    volumes:
      - /var/lib/docker/volumes:/data
      - instance-storage:/config
    environment:
      - FB_BASEURL=/filebrowser
    restart: always

volumes:
  instance-storage:
    external: false
    name: filebrowser
